const SOLO_RATES=[[0,2000,125],[2000,3000,150],[3000,3500,185],[3500,4000,250],[4000,4500,300],[4500,5000,330],[5000,5620,400],[5620,6000,700],[6000,6500,900],[6500,7000,1200],[7000,7500,1500],[7500,8000,2000],[8000,8500,3000],[8500,9000,6000],[9000,9500,10000]];
const PARTY_RATES=[[0,2000,70],[2000,3000,80],[3000,4000,90],[4000,4500,110],[4500,5000,150],[5000,5620,180],[5620,6000,250],[6000,6500,400],[6500,7000,750],[7000,7500,1000],[7500,8000,2000],[8000,8500,3000],[8500,9000,4000],[9000,9500,5000]];
const CAL_RATES=[[0,2000,55],[2000,3000,65],[3000,4000,75],[4000,4500,90],[4500,5000,100],[5000,5620,135],[5620,6000,250],[6000,6500,300],[6500,7000,450],[7000,7500,600],[7500,8000,1000],[8000,8500,2000],[8500,9000,3500],[9000,9500,5000]];
const SERVICES={solo:{title:'ММР буст',subtitle:'Плавный рост',rates:SOLO_RATES,unit:'₽ / 100 MMR'},party:{title:'Пати буст',subtitle:'С клиентом',rates:PARTY_RATES,unit:'₽ / вин'},calibration:{title:'Калибровка',subtitle:'Передача аккаунта',rates:CAL_RATES,unit:'₽ / вин'},coaching:{title:'Коучинг',subtitle:'Индивидуально',rates:null,unit:'₽ / час'},battlecup:{title:'Боевой кубок',subtitle:'С передачей',rates:null,unit:'₽ / заказ'}};
const DEFAULT={current:1000,target:3000,mmr:3000,wins:10,hours:1,tier:3,order:10000,courtesy:10000};
const state={service:'solo',values:{...DEFAULT},addons:{doubles:false,core:false,smurfpool:false},breakdownOpen:false,orderReference:null};
let lastCalculation={service:'solo',route:'',base:0,total:0,pct:0,addonRows:[],estimatedGames:0,extraRows:[]};
const STORAGE_KEY='dota_boost_v4';
const HISTORY_KEY='dota_boost_v4_history';
const $=s=>document.querySelector(s);
const money=v=>`${Math.round(v).toLocaleString('ru-RU')} ₽`;
const fmt=v=>Math.round(v).toLocaleString('ru-RU');
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));

function rateFor(m,rates){const n=Number(m)||0;if(!rates)return 0;const hit=rates.find(([a,b])=>n>=a&&n<b);return hit?hit[2]:rates[rates.length-1][2]}
function progressiveRows(a,b,rates){return D2Pricing.progressiveBreakdown(a,b,rates)}
function bandCount(a,b,rates){return D2Pricing.bandCount(a,b,rates)}
function parseFieldValue(value){const raw=String(value??'').replace(',','.').replace(/[^0-9.]/g,'');const n=Number(raw);return Number.isFinite(n)?n:0}
function quickButtons(id,values){return values.map(v=>`<button type="button" class="quick-preset" data-for="${id}" data-value="${v}">${fmt(v)}</button>`).join('')}
function statusBadge(value,kind){if(kind==='order')return value<9000?'<span class="status-badge warn">+20%</span>':'<span class="status-badge good">Без доплаты</span>';if(value<6000)return '<span class="status-badge danger">+20%</span>';if(value<8000)return '<span class="status-badge warn">+10%</span>';return '<span class="status-badge good">Без доплаты</span>'}
function numberField(id,label,value,min,max,step,help,quick=''){
 const inputmode=Number(step)%1===0?'numeric':'decimal';
 return `<div class="field"><label for="${id}">${label}</label><div class="number-control"><button type="button" class="number-step" data-for="${id}" data-step="-${step}" aria-label="Уменьшить ${label}">−</button><input id="${id}" class="number-input" type="text" inputmode="${inputmode}" autocomplete="off" value="${String(value).replace('.',',')}" data-min="${min}" data-max="${max}" data-step="${step}" aria-label="${label}"><button type="button" class="number-step" data-for="${id}" data-step="${step}" aria-label="Увеличить ${label}">+</button></div>${quick?`<div class="quick-presets" aria-label="Быстрый выбор">${quick}</div>`:''}<small>${help}</small></div>`;
}

const OPTION_ICONS={
 doubles:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8l2 4-2 4H8L6 7z"/><path d="M6 13h12l2 4-2 4H6l-2-4z"/><path d="M9 6h6M9 17h6"/></svg>',
 core:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4l5 5 5-5 2 3-4 4 4 4-2 3-5-5-5 5-2-3 4-4-4-4z"/></svg>',
 smurfpool:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 11c0-4 3.6-7 8-7s8 3 8 7v4c0 3-3 5-6 5H10c-3 0-6-2-6-5z"/><path d="M8 11h.01M16 11h.01M9 16c2 1 4 1 6 0"/></svg>'
};
function addonDefs(service){return [
 ['doubles','Двойной жетон победы',service==='party'?'до 5620: +50% · от 5620: +30%':'от 5620: +30%',m=>D2Pricing.isAddonEligible(service,'doubles',m)],
 ['core','Игра на кор роли','+100% к стоимости',()=>true],
 ['smurfpool','Смурфпулл','от 3500 MMR · +15%',m=>D2Pricing.isAddonEligible(service,'smurfpool',m)]
]}
function renderOptions(service,mmr){return addonDefs(service).map(([id,title,desc,eligibleFn])=>{const eligible=eligibleFn(mmr);const checked=!!state.addons[id]&&eligible;return `<label class="option option-${id} ${eligible?'':'disabled-option'}"><span class="option-icon">${OPTION_ICONS[id]||''}</span><span class="option-copy"><span class="option-title">${title}${eligible?'':'<span class="hint-badge">Недоступно</span>'}</span><span class="option-desc">${desc}</span></span><span class="switch"><input type="checkbox" data-addon="${id}" role="switch" ${checked?'checked':''} ${eligible?'':'disabled'} aria-label="${title}" aria-checked="${checked}"><span class="switch-track"><span class="switch-thumb"></span></span></span></label>`}).join('')}
function sectionTitle(num,title,copy=''){return `<div class="form-step-heading"><span class="form-step-number">${num}</span><div><strong>${title}</strong>${copy?`<small>${copy}</small>`:''}</div></div>`}
function renderFields(){
 const s=state.service;
 $('#serviceTitle').textContent=SERVICES[s].title;$('#serviceSubtitle').textContent=SERVICES[s].subtitle;
 if(s==='solo'){
  $('#formArea').innerHTML=`<div class="form-grid">${sectionTitle('01','Параметры','Выбери точку старта и цель')}${numberField('current','Текущий MMR',state.values.current,0,9500,100,'Точка старта буста',quickButtons('current',[2000,3000,4000,5000]))}${numberField('target','Желаемый MMR',state.values.target,0,9500,100,'Конечный MMR',quickButtons('target',[4000,5000,6000,7000]))}<div class="field full"><div class="metrics"><div><span>Буст</span><strong id="metricMmr">—</strong></div><div><span>Диапазонов</span><strong id="metricBands">—</strong></div><div><span>Ориентир игр</span><strong id="metricWins">—</strong></div></div><div class="mmr-scale" id="mmrScale"></div></div><div class="field full"><div class="field-help"><span>ⓘ</span><p>Цена ММР считается прогрессивно: каждый участок пути оплачивается по своей ставке. Ориентир игр — при +30 MMR за победу; показатель не влияет на цену.</p></div></div>${sectionTitle('02','Дополнительные условия','Только реальные переключаемые опции')}<div class="field full option-section"><div class="options">${renderOptions('solo',Math.max(state.values.current,state.values.target))}</div></div>${sectionTitle('03','Аккаунт','Порядочность и вежливость влияют автоматически')}${numberField('order','Порядочность аккаунта',state.values.order,0,12000,100,statusBadge(state.values.order,'order'),quickButtons('order',[6000,8000,9000,10000]))}${numberField('courtesy','Вежливость аккаунта',state.values.courtesy,0,12000,100,statusBadge(state.values.courtesy,'courtesy'),quickButtons('courtesy',[5000,6000,8000,10000]))}</div>`;
 } else if(s==='party'||s==='calibration'){
  $('#formArea').innerHTML=`<div class="form-grid">${sectionTitle('01','Параметры',s==='party'?'MMR клиента и количество побед':'MMR аккаунта и количество побед')}${numberField('mmr',s==='party'?'MMR клиента':'MMR аккаунта',state.values.mmr,0,9500,100,'По этому MMR выбирается стартовая ставка',quickButtons('mmr',[3000,4000,5000,5620,6000]))}${numberField('wins','Количество вин',state.values.wins,1,1000,1,s==='party'?'Победы вместе с клиентом':'Победы при калибровке',quickButtons('wins',[5,10,20,30]))}${s==='party'?'<div class="field full party-journey" id="partyJourney"></div>':''}${sectionTitle('02','Дополнительные условия','Наценка считается от базовой суммы') }<div class="field full option-section"><div class="options">${renderOptions(s,state.values.mmr)}</div></div>${sectionTitle('03','Аккаунт','Показатели аккаунта учитываются автоматически')}${numberField('order','Порядочность аккаунта',state.values.order,0,12000,100,statusBadge(state.values.order,'order'),quickButtons('order',[6000,8000,9000,10000]))}${numberField('courtesy','Вежливость аккаунта',state.values.courtesy,0,12000,100,statusBadge(state.values.courtesy,'courtesy'),quickButtons('courtesy',[5000,6000,8000,10000]))}</div>`;
 } else if(s==='coaching'){
  $('#formArea').innerHTML=`<div class="form-grid">${sectionTitle('01','Параметры','Выбери MMR клиента и длительность')}${numberField('mmr','MMR клиента',state.values.mmr,0,12000,100,'0–5629: 330 ₽ · 5630–6999: 500 ₽ · 7000+: 700 ₽',quickButtons('mmr',[3000,5000,7000,8000]))}${numberField('hours','Количество часов',state.values.hours,0.5,100,0.5,'Шаг 0,5 часа',quickButtons('hours',[1,2,4,8]))}</div>`;
 } else {
  const prices={3:200,4:250,5:300,6:400,7:500,8:1000};
  $('#formArea').innerHTML=`<div class="form-grid">${sectionTitle('01','Параметры','Выбери нужный тир') }<div class="field full"><label for="tier">Тир боевого кубка</label><select id="tier">${[3,4,5,6,7,8].map(t=>`<option value="${t}">${t} тир — ${money(prices[t])}</option>`).join('')}</select><small>Услуга с передачей аккаунта</small></div></div>`;$('#tier').value=state.values.tier;
 }
 bindFields();updateMetrics();calculate();refreshOptionEligibility();updateStepIndicators();
}
function bindFields(){
 document.querySelectorAll('#formArea input,#formArea select').forEach(el=>{el.addEventListener('input',onInput);el.addEventListener('change',onInput);el.addEventListener('blur',()=>commitField(el));});
 document.querySelectorAll('.number-step').forEach(btn=>btn.addEventListener('click',()=>{const input=$(`#${btn.dataset.for}`);if(!input)return;const min=Number(input.dataset.min)||0,max=Number(input.dataset.max)||9500,step=Number(input.dataset.step)||1;const next=Math.min(max,Math.max(min,parseFieldValue(input.value)+Number(btn.dataset.step)));input.value=String(Number(next.toFixed(2))).replace('.',',');onInput({target:input});input.focus();}));
 document.querySelectorAll('.quick-preset').forEach(btn=>btn.addEventListener('click',()=>{const input=$(`#${btn.dataset.for}`);if(!input)return;input.value=String(btn.dataset.value).replace('.',',');onInput({target:input});input.focus();}));
}
function commitField(el){if(!el?.dataset.step)return;const min=Number(el.dataset.min)||0,max=Number(el.dataset.max)||9500;const n=Math.min(max,Math.max(min,parseFieldValue(el.value)));el.value=String(n).replace('.',',');state.values[el.id]=n;normalizeState();renderFields();}
function onInput(e){const el=e.target;if(el.dataset.addon){state.addons[el.dataset.addon]=el.checked;el.setAttribute('aria-checked',String(el.checked));calculate();refreshOptionEligibility();updateStepIndicators();return}if(el.id in state.values){let cleaned=String(el.value).replace(/[^0-9.,]/g,'').replace(/(,.*),/g,'$1');if(el.value!==cleaned)el.value=cleaned;state.values[el.id]=parseFieldValue(cleaned);if(el.id==='current'&&state.values.target<state.values.current){state.values.target=state.values.current;const t=$('#target');if(t)t.value=String(state.values.target)}if(el.id==='target'&&state.values.target<state.values.current){state.values.target=state.values.current;el.value=String(state.values.target)}normalizeState();calculate();refreshOptionEligibility();updateStepIndicators();}}
function normalizeState(){state.values.current=clamp(state.values.current,0,9500);state.values.target=clamp(state.values.target,state.values.current,9500);state.values.mmr=clamp(state.values.mmr,0,9500);state.values.wins=clamp(state.values.wins,1,1000);state.values.hours=clamp(state.values.hours,.5,100);state.values.tier=clamp(state.values.tier,3,8);state.values.order=clamp(state.values.order,0,12000);state.values.courtesy=clamp(state.values.courtesy,0,12000)}
function updateStepIndicators(){const steps=document.querySelectorAll('.form-steps .step');if(!steps.length)return;steps.forEach((s,i)=>s.classList.toggle('active',i===0));steps[1]?.classList.toggle('complete',Object.values(state.addons).some(Boolean));steps[2]?.classList.toggle('complete',state.values.order!==10000||state.values.courtesy!==10000)}
function refreshOptionEligibility(){const mmr=state.service==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr;document.querySelectorAll('[data-addon]').forEach(input=>{const def=addonDefs(state.service).find(x=>x[0]===input.dataset.addon);if(!def)return;const eligible=def[3](mmr);input.disabled=!eligible;if(!eligible){input.checked=false;state.addons[input.dataset.addon]=false;}const card=input.closest('.option');card?.classList.toggle('disabled-option',!eligible);input.setAttribute('aria-checked',String(input.checked));});saveState();}
function updateMetrics(){if(state.service==='solo'){const add=Math.max(0,state.values.target-state.values.current);const wins=D2Pricing.soloWinEstimate(state.values.current,state.values.target,D2Pricing.SOLO_MMR_PER_WIN);$('#metricMmr').textContent=`+${fmt(add)} MMR`;$('#metricBands').textContent=String(bandCount(state.values.current,state.values.target,SOLO_RATES));$('#metricWins').textContent=wins?`≈ ${fmt(wins)} игр`:'—';renderMmrScale(state.values.current,state.values.target,SOLO_RATES,'solo');}}
function renderMmrScale(start,target,rates,mode='solo'){
 const box=$('#mmrScale');if(!box)return;const rows=progressiveRows(start,target,rates);if(!rows.length){box.innerHTML='<div class="scale-empty">Выбери MMR выше текущего значения</div>';return}
 const total=Math.max(1,rows.reduce((s,r)=>s+r.mmr,0));
 const segments=rows.map(r=>`<span style="flex-basis:${Math.max(4,r.mmr/total*100)}%" title="${fmt(r.from)}–${fmt(r.to)} · ${money(r.rate)} / 100">${r.mmr>=300?fmt(r.to):''}</span>`).join('');
 box.innerHTML=`<div class="scale-head"><b>${fmt(start)}</b><span>${mode==='solo'?`${rows.length} тарифных диапазонов`:''}</span><b>${fmt(target)}</b></div><div class="scale-bar">${segments}</div><div class="scale-labels">${rows.map(r=>`<span>${fmt(r.rate)} ₽</span>`).join('')}</div>`;
}
function coachingRate(m){return m>=7000?700:m>=5630?500:330}
function battleRate(t){return({3:200,4:250,5:300,6:400,7:500,8:1000})[t]||0}
function addonRows(mmr,service,base){return D2Pricing.addonBreakdown(mmr,state.addons,service,state.values.order,state.values.courtesy).map(x=>({...x,amount:base*x.percent}));}
function renderPartyJourney(result,doubles){const box=$('#partyJourney');if(!box)return;const gainBefore=doubles?80:40;const gainAfter=doubles?50:25;const pieces=result.segments.map(seg=>`<div class="party-segment"><div><strong>${fmt(seg.from)} → ${fmt(seg.to)} MMR</strong><span>${seg.games} ${seg.games===1?'игра':'игр'} · +${fmt(seg.gain)} MMR</span></div><b>${money(seg.rate)} / игра</b><em>${money(seg.cost)}</em></div>`).join('');box.innerHTML=`<div class="party-journey-card"><div class="party-journey-head"><div><small>КАК СЧИТАЕТСЯ ПАТИ БУСТ</small><strong>${doubles?'Жетон включён':'Без жетона'} · +${gainBefore} MMR до 4000 · +${gainAfter} MMR после 4000</strong></div><span>${fmt(result.startMmr)} → ${fmt(result.endMmr)} MMR</span></div><div class="party-legend"><span>Цена меняется при переходе в новый MMR-диапазон</span><span>Всего ${fmt(result.totalGames)} игр · ${money(result.totalCost)}</span></div><div class="party-segments">${pieces}</div></div>`}
function calculate(){
 const s=state.service;let total=0,base=0,pct=0,route='';let rows=[];let addonBaseMmr=0;let extraRows=[];let estimatedGames=0;
 if(s==='solo'){const a=state.values.current,b=state.values.target,segments=progressiveRows(a,b,SOLO_RATES);base=segments.reduce((sum,row)=>sum+row.cost,0);addonBaseMmr=Math.max(a,b);pct=D2Pricing.addonPercent(addonBaseMmr,state.addons,'standard',state.values.order,state.values.courtesy);route=`${fmt(a)} → ${fmt(b)} MMR`;estimatedGames=D2Pricing.soloWinEstimate(a,b,D2Pricing.SOLO_MMR_PER_WIN);rows=[['Базовая стоимость',money(base)],['MMR к бусту',`+${fmt(Math.max(0,b-a))}`],['Ориентировочно игр',estimatedGames?`≈ ${fmt(estimatedGames)}`:'—']];extraRows=segments.map(row=>({label:`${fmt(row.from)}–${fmt(row.to)} MMR`,value:money(row.cost),rate:row.rate}));renderMmrScale(a,b,SOLO_RATES,'solo');}
 else if(s==='party'){const m=state.values.mmr,wins=state.values.wins,doubles=!!state.addons.doubles,party=D2Pricing.partyBreakdown(m,wins,doubles);base=party.totalCost;addonBaseMmr=m;pct=D2Pricing.addonPercent(m,state.addons,'party',state.values.order,state.values.courtesy);route=`${fmt(m)} → ${fmt(party.endMmr)} MMR · ${fmt(wins)} побед`;rows=[['Количество игр',fmt(wins)],['MMR за игру',doubles?(m<4000?'+80 до 4000 / +50 после':'+50 MMR за игру'):(m<4000?'+40 до 4000 / +25 после':'+25 MMR за игру')]];extraRows=party.segments.map(seg=>({label:`${fmt(seg.from)}–${fmt(seg.to)} MMR`,value:money(seg.cost),rate:seg.rate,games:seg.games}));renderPartyJourney(party,doubles);}
 else if(s==='calibration'){const m=state.values.mmr,wins=state.values.wins,rate=rateFor(m,CAL_RATES);base=rate*wins;addonBaseMmr=m;pct=D2Pricing.addonPercent(m,state.addons,'calibration',state.values.order,state.values.courtesy);route=`${fmt(m)} MMR · ${fmt(wins)} побед`;rows=[['Ставка',`${money(rate)} / вин`],['Победы',fmt(wins)]];$('#partyJourney')?.remove();}
 else if(s==='coaching'){const m=state.values.mmr,h=state.values.hours,rate=coachingRate(m);base=rate*h;total=base;route=`${fmt(m)} MMR · ${h.toLocaleString('ru-RU')} ч`;rows=[['Ставка',`${money(rate)} / час`],['Часы',h.toLocaleString('ru-RU')]]}
 else{const tier=Number(state.values.tier)||3;base=battleRate(tier);total=base;route=`${tier} тир · передача аккаунта`;rows=[['Тир',`${tier} тир`],['Формат','С передачей']]}
 let addons=[];
 if(['solo','party','calibration'].includes(s)){addons=addonRows(addonBaseMmr,s,base);total=base*(1+pct);rows.push(['<strong>База</strong>',money(base)]);rows.push(...addons.map(x=>[`<span class="breakdown-addon">${x.label}</span>`,`+${Math.round(x.percent*100)}% · ${money(x.amount)}`]));rows.push(['<strong>Доплаты</strong>',pct?`+${Math.round(pct*100)}%`:'Нет']);rows.push(['<strong>Итого доплат</strong>',money(base*pct)]);renderBreakdown(rows);}
 else renderBreakdown(rows);
 const priceChip=s==='solo'?`${money(rateFor(Math.max(state.values.current,state.values.target),SOLO_RATES))} / 100 MMR`:s==='coaching'?`${money(coachingRate(state.values.mmr))} / час`:s==='battlecup'?`${money(base)} / заказ`:`${money(rateFor(state.values.mmr,SERVICES[s].rates))} / вин`;
 lastCalculation={service:s,route,base,total,pct,addonRows:addons,estimatedGames,extraRows,order:state.values.order,courtesy:state.values.courtesy};
 $('#chipPrice').textContent=priceChip;$('#routeLine').textContent=route;$('#totalPrice').textContent=money(total);$('#resultNote').textContent='Цена обновляется автоматически';
 updatePrimarySummary(s,base,pct,total);refreshStatuses();updateTable();saveState();updateModalPreview();
}
function updatePrimarySummary(service,base,pct,total){const box=$('#summaryPreview');if(!box)return;const addonRowsData=addonRows(service==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr,service,base);box.innerHTML=`<div class="summary-row"><span>База</span><strong>${money(base)}</strong></div>${addonRowsData.slice(0,2).map(x=>`<div class="summary-row compact-addon"><span>${x.label}</span><strong>+${Math.round(x.percent*100)}%</strong></div>`).join('')}<div class="summary-total-row"><span>Итого</span><strong>${money(total)}</strong></div>`;}
function renderBreakdown(rows){const detail=$('#summaryDetail');if(!detail)return;detail.innerHTML=rows.map(r=>`<div class="summary-row detail-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('');detail.hidden=!state.breakdownOpen;const btn=$('#breakdownToggle');if(btn){btn.setAttribute('aria-expanded',String(state.breakdownOpen));btn.classList.toggle('open',state.breakdownOpen);}}
function toggleBreakdown(){state.breakdownOpen=!state.breakdownOpen;const d=$('#summaryDetail');const b=$('#breakdownToggle');if(d)d.hidden=!state.breakdownOpen;if(b){b.setAttribute('aria-expanded',String(state.breakdownOpen));b.classList.toggle('open',state.breakdownOpen);}}
function refreshStatuses(){document.querySelectorAll('.status-badge').forEach(el=>{const input=el.closest('.field')?.querySelector('input');const id=input?.id;if(!id)return;el.outerHTML=id==='order'?statusBadge(state.values.order,'order'):statusBadge(state.values.courtesy,'courtesy');});}
function updateTable(){const s=state.service;$('#tableTitle').textContent=s==='solo'?'Тарифы ММР буста':`Прайс — ${SERVICES[s].title}`;const head=$('#priceTableHead'),body=$('#priceTableBody');if(['solo','party','calibration'].includes(s)){const rates=SERVICES[s].rates;head.innerHTML='<th>Диапазон MMR</th><th>Ставка</th>';body.innerHTML=rates.map(([a,b,r])=>`<tr><td>${fmt(a)}–${fmt(b)}</td><td>${money(r)} / ${s==='solo'?'100 MMR':'вин'}</td></tr>`).join('');$('#tableHint').textContent=s==='solo'?'₽ / 100 MMR':'₽ / вин';return}if(s==='coaching'){head.innerHTML='<th>MMR</th><th>Ставка</th>';body.innerHTML='<tr><td>0–5629</td><td>330 ₽ / час</td></tr><tr><td>5630–6999</td><td>500 ₽ / час</td></tr><tr><td>7000+</td><td>700 ₽ / час</td></tr>';$('#tableHint').textContent='₽ / час';return}head.innerHTML='<th>Тир</th><th>Цена</th><th>Формат</th>';body.innerHTML=[[3,200],[4,250],[5,300],[6,400],[7,500],[8,1000]].map(x=>`<tr><td>${x[0]} тир</td><td>${money(x[1])}</td><td>С передачей</td></tr>`).join('');$('#tableHint').textContent='₽ / заказ';}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.values){Object.assign(state.values,saved.values);state.service=SERVICES[saved.service]?saved.service:'solo';state.addons={doubles:!!saved.addons?.doubles,core:!!saved.addons?.core,smurfpool:!!saved.addons?.smurfpool};}normalizeState();}catch{}}
function saveHistory(){const item={service:SERVICES[state.service].title,route:$('#routeLine').textContent,total:$('#totalPrice').textContent,at:new Date().toLocaleString('ru-RU')};try{const list=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');localStorage.setItem(HISTORY_KEY,JSON.stringify([item,...list].slice(0,6)));renderHistory();}catch{}}
function renderHistory(){const box=$('#historyList');if(!box)return;try{const list=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');box.innerHTML=list.length?list.map(x=>`<button class="history-item" type="button"><span><strong>${x.service}</strong><small>${x.route} · ${x.at}</small></span><b>${x.total}</b></button>`).join(''):'<div class="empty-history">История пока пуста</div>';}catch{box.textContent='История пока недоступна'}}
function selectedAddons(){return D2Pricing.addonBreakdown(state.service==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr,state.addons,state.service,state.values.order,state.values.courtesy)}
function generateOrderReference(){return `D2-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
function buildOrderSummaryModel(input){
 const src=input||{...lastCalculation,reference:state.orderReference||generateOrderReference()};
 const addonRows=(src.addons||src.addonRows||[]).map(x=>({...x}));
 const addonTotal=Number.isFinite(src.addonTotal)?src.addonTotal:addonRows.reduce((sum,x)=>sum+(Number(x.amount)||0),0);
 return {reference:src.reference||state.orderReference||generateOrderReference(),serviceId:src.serviceId||src.service,service:src.serviceTitle||SERVICES[src.service]?.title||src.service,route:src.route||'',baseLabel:'Базовая стоимость',base:Number(src.base)||0,addonRows,addonTotal,total:Number(src.total)||0,order:src.order,courtesy:src.courtesy,estimatedGames:src.estimatedGames||0,extraRows:src.extraRows||[]};
}
function buildOrderMessage(summary){const lines=[`🔥 DOTA BOOST — ЗАКАЗ`,`Номер: ${summary.reference}`,`Услуга: ${summary.service}`,`Параметры: ${summary.route}`];if(summary.estimatedGames)lines.push(`Ориентировочно игр: ${fmt(summary.estimatedGames)}`);if(['solo','party','calibration'].includes(summary.serviceId)){lines.push(`Порядочность: ${fmt(summary.order)}`,`Вежливость: ${fmt(summary.courtesy)}`);}lines.push('',`Базовая стоимость: ${money(summary.base)}`);if(summary.addonRows.length){lines.push('Доплаты:');summary.addonRows.forEach(a=>lines.push(`• ${a.label} +${Math.round(a.percent*100)}% — ${money(a.amount)}`));lines.push(`Итого доплат: ${money(summary.addonTotal)}`);}lines.push('',`💰 Итого: ${money(summary.total)}`);return lines.join('\n')}
function buildOrderText(){return buildOrderMessage(buildOrderSummaryModel())}
function buildOrderSummaryHtml(){const s=buildOrderSummaryModel();const account=['solo','party','calibration'].includes(state.service)?`<div class="modal-line"><span>Порядочность</span><strong>${fmt(s.order)}</strong></div><div class="modal-line"><span>Вежливость</span><strong>${fmt(s.courtesy)}</strong></div>`:'';const games=s.estimatedGames?`<div class="modal-line"><span>Ориентир игр</span><strong>≈ ${fmt(s.estimatedGames)}</strong></div>`:'';const segments=s.extraRows.length?`<div class="modal-subhead">Разбивка</div>${s.extraRows.map(r=>`<div class="modal-line modal-line-muted"><span>${r.label}${r.games?` · ${r.games} игр`:''}</span><strong>${r.value}</strong></div>`).join('')}`:'';const addons=s.addonRows.length?`<div class="modal-subhead">Дополнительные условия</div>${s.addonRows.map(a=>`<div class="modal-line"><span>${a.label}</span><strong>+${Math.round(a.percent*100)}% · ${money(a.amount)}</strong></div>`).join('')}`:'';return `<div class="modal-ref">${s.reference}</div><div class="modal-line"><span>Услуга</span><strong>${s.service}</strong></div><div class="modal-line"><span>Параметры</span><strong>${s.route}</strong></div>${games}${account}<div class="modal-subhead">Стоимость</div><div class="modal-line"><span>${s.baseLabel}</span><strong>${money(s.base)}</strong></div>${addons}<div class="modal-line"><span>Итого доплат</span><strong>${money(s.addonTotal)}</strong></div>${segments}<div class="modal-note">Цена предварительная. Финальная стоимость фиксируется после подтверждения.</div>`}
function updateModalPreview(){if(!$('#orderModal')?.classList.contains('open'))return;const summary=buildOrderSummaryModel();$('#modalSummary').innerHTML=buildOrderSummaryHtml();$('#modalTotal').textContent=money(summary.total);$('#modalRef').textContent=summary.reference;}
function openOrderModal(){state.orderReference=generateOrderReference();saveState();$('#modalSummary').innerHTML=buildOrderSummaryHtml();$('#modalTotal').textContent=$('#totalPrice').textContent;$('#modalRef').textContent=state.orderReference;const modal=$('#orderModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('#modalConfirm')?.focus();}
function closeOrderModal(){const modal=$('#orderModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');$('#orderBtn')?.focus();}
function confirmTelegramOrder(){const text=encodeURIComponent(buildOrderText());saveHistory();window.open(`https://t.me/share/url?url=${encodeURIComponent(location.href)}&text=${text}`,'_blank','noopener');closeOrderModal();}
function copyCalc(){try{navigator.clipboard.writeText(buildOrderText()).then(()=>{$('#copyStatus').textContent='Расчёт скопирован';setTimeout(()=>$('#copyStatus').textContent='',1800)});}catch{$('#copyStatus').textContent='Не удалось скопировать'}}
function switchService(s){state.service=s;state.breakdownOpen=false;document.querySelectorAll('.service-tab').forEach(b=>b.classList.toggle('active',b.dataset.service===s));renderFields();window.scrollTo({top:document.querySelector('.service-nav').offsetTop-12,behavior:'smooth'});}
function reset(){state.service='solo';state.values={...DEFAULT};state.addons={doubles:false,core:false,smurfpool:false};state.breakdownOpen=false;saveState();renderFields();}
if (typeof document === 'undefined') {
  globalThis.__D2App = { buildOrderSummaryModel, buildOrderMessage };
} else {
loadState();
document.querySelectorAll('.service-tab').forEach(b=>b.addEventListener('click',()=>switchService(b.dataset.service)));
$('#resetBtn').addEventListener('click',reset);
$('#copyBtn').addEventListener('click',copyCalc);
$('#orderBtn').addEventListener('click',openOrderModal);
$('#saveCalcBtn')?.addEventListener('click',saveHistory);
$('#breakdownToggle')?.addEventListener('click',toggleBreakdown);
$('#modalClose')?.addEventListener('click',closeOrderModal);
$('#modalCancel')?.addEventListener('click',closeOrderModal);
$('#modalConfirm')?.addEventListener('click',confirmTelegramOrder);
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeOrderModal));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#orderModal')?.classList.contains('open'))closeOrderModal()});
renderFields();renderHistory();
}
