const SOLO_RATES=[[0,2000,125],[2000,3000,150],[3000,3500,185],[3500,4000,250],[4000,4500,300],[4500,5000,330],[5000,5620,400],[5620,6000,700],[6000,6500,900],[6500,7000,1200],[7000,7500,1500],[7500,8000,2000],[8000,8500,3000],[8500,9000,6000],[9000,9500,10000]];
const PARTY_RATES=[[0,2000,70],[2000,3000,80],[3000,4000,90],[4000,4500,110],[4500,5000,150],[5000,5620,180],[5620,6000,250],[6000,6500,400],[6500,7000,750],[7000,7500,1000],[7500,8000,2000],[8000,8500,3000],[8500,9000,4000],[9000,9500,5000]];
const CAL_RATES=[[0,2000,55],[2000,3000,65],[3000,4000,75],[4000,4500,90],[4500,5000,100],[5000,5620,135],[5620,6000,250],[6000,6500,300],[6500,7000,450],[7000,7500,600],[7500,8000,1000],[8000,8500,2000],[8500,9000,3500],[9000,9500,5000]];
const SERVICES={solo:{title:'ММР буст',subtitle:'Плавный рост',rates:SOLO_RATES,unit:'₽ / 100 MMR'},party:{title:'Пати буст',subtitle:'С клиентом',rates:PARTY_RATES,unit:'₽ / вин'},calibration:{title:'Калибровка',subtitle:'Передача аккаунта',rates:CAL_RATES,unit:'₽ / вин'},coaching:{title:'Коучинг',subtitle:'Индивидуально',rates:null,unit:'₽ / час'},battlecup:{title:'Боевой кубок',subtitle:'С передачей',rates:null,unit:'₽ / заказ'}};
const DEFAULT={current:1000,target:3000,mmr:3000,wins:10,hours:1,tier:3,order:10000,courtesy:10000};
const state={service:'solo',values:{...DEFAULT},addons:{}};
const STORAGE_KEY='dota_boost_v3';
const HISTORY_KEY='dota_boost_v3_history';
const $=s=>document.querySelector(s); const money=v=>`${Math.round(v).toLocaleString('ru-RU')} ₽`; const fmt=v=>Math.round(v).toLocaleString('ru-RU');
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
function rateFor(m,rates){const n=Number(m)||0;if(!rates)return 0;const hit=rates.find(([a,b])=>n>=a&&n<b);return hit?hit[2]:rates[rates.length-1][2]}
function progressive(a,b,rates){const from=Math.min(clamp(a,0,9500),clamp(b,0,9500)),to=Math.max(clamp(a,0,9500),clamp(b,0,9500));return rates.reduce((sum,[lo,hi,rate])=>sum+Math.max(0,Math.min(to,hi)-Math.max(from,lo))/100*rate,0)}
function bandCount(a,b,rates){const from=Math.min(a,b),to=Math.max(a,b);return rates.filter(([lo,hi])=>from<hi&&to>lo).length}
function addonDefs(service){return [
 ['doubles','Двойной жетон победы',service==='party'?'до 5620: +50% · от 5620: +30%':'от 5620: +30%',m=>D2Pricing.isAddonEligible(service,'doubles',m)],
 ['core','Игра на кор роли','+100% к стоимости',()=>true],
 ['smurfpool','Смурфпулл','от 3500 MMR · +15%',m=>D2Pricing.isAddonEligible(service,'smurfpool',m)]
]}
function numberField(id,label,value,min,max,step,help,quick=''){
 const inputmode=Number(step)%1===0?'numeric':'decimal';
 return `<div class="field"><label for="${id}">${label}</label><div class="number-control"><button type="button" class="number-step" data-for="${id}" data-step="-${step}" aria-label="Уменьшить ${label}">−</button><input id="${id}" class="number-input" type="text" inputmode="${inputmode}" autocomplete="off" value="${String(value).replace('.',',')}" data-min="${min}" data-max="${max}" data-step="${step}" aria-label="${label}"><button type="button" class="number-step" data-for="${id}" data-step="${step}" aria-label="Увеличить ${label}">+</button></div>${quick?`<div class="quick-presets" aria-label="Быстрый выбор">${quick}</div>`:''}<small>${help}</small></div>`;
}
function parseFieldValue(value){const raw=String(value??'').replace(',', '.').replace(/[^0-9.]/g,'');const n=Number(raw);return Number.isFinite(n)?n:0}
function quickButtons(id,values){return values.map(v=>`<button type="button" class="quick-preset" data-for="${id}" data-value="${v}">${fmt(v)}</button>`).join('')}
function renderOptions(service,mmr){return addonDefs(service).map(([id,title,desc,eligibleFn])=>{const eligible=eligibleFn(mmr);const checked=!!state.addons[id]&&eligible;return `<label class="option ${eligible?'':'disabled-option'}"><span class="option-copy"><span class="option-title">${title}${eligible?'':'<span class="hint-badge">Недоступно</span>'}</span><span class="option-desc">${desc}</span></span><span class="switch"><input type="checkbox" data-addon="${id}" role="switch" ${checked?'checked':''} ${eligible?'':'disabled'} aria-label="${title}" aria-checked="${checked}"><span class="switch-track"><span class="switch-thumb"></span></span></span></label>`}).join('')}
function statusBadge(value,kind){if(kind==='order'){return value<9000?'<span class="status-badge warn">+20%</span>':'<span class="status-badge good">Без доплаты</span>'}if(value<6000)return '<span class="status-badge danger">+20%</span>';if(value<8000)return '<span class="status-badge warn">+10%</span>';return '<span class="status-badge good">Без доплаты</span>'}
function renderFields(){const s=state.service;$('#serviceTitle').textContent=SERVICES[s].title;$('#serviceSubtitle').textContent=SERVICES[s].subtitle;
 if(s==='solo'){$('#formArea').innerHTML=`<div class="form-grid">${numberField('current','Текущий MMR',state.values.current,0,9500,100,'Точка старта буста',quickButtons('current',[2000,3000,4000,5000]))}${numberField('target','Желаемый MMR',state.values.target,1,9500,100,'Конечный MMR',quickButtons('target',[4000,5000,6000,7000]))}<div class="field full"><div class="metrics"><div><span>Буст</span><strong id="metricMmr">—</strong></div><div><span>Ценовых диапазонов</span><strong id="metricBands">—</strong></div></div></div><div class="field-help full">Цена ММР считается прогрессивно: каждый участок пути оплачивается по своей ставке.</div><div class="field full option-section"><div class="section-line"><strong>Дополнительные условия</strong><span>Включайте только нужные</span></div><div class="options">${renderOptions('solo',Math.max(state.values.current,state.values.target))}</div></div>${numberField('order','Порядность аккаунта',state.values.order,0,12000,100,statusBadge(state.values.order,'order'),quickButtons('order',[6000,8000,9000,10000]))}${numberField('courtesy','Вежливость аккаунта',state.values.courtesy,0,12000,100,statusBadge(state.values.courtesy,'courtesy'),quickButtons('courtesy',[5000,6000,8000,10000]))}</div>`}
 else if(s==='party'||s==='calibration'){$('#formArea').innerHTML=`<div class="form-grid">${numberField('mmr',s==='party'?'MMR клиента':'MMR аккаунта',state.values.mmr,0,9500,100,'По этому MMR выбирается ставка',quickButtons('mmr',[3000,4000,5000,5620,6000]))}${numberField('wins','Количество вин',state.values.wins,1,1000,1,s==='party'?'Победы вместе с клиентом':'Победы при калибровке',quickButtons('wins',[5,10,20,30]))}<div class="field full option-section"><div class="section-line"><strong>Дополнительные условия</strong><span>Наценка считается от всей суммы</span></div><div class="options">${renderOptions(s,state.values.mmr)}</div></div>${numberField('order','Порядность аккаунта',state.values.order,0,12000,100,statusBadge(state.values.order,'order'),quickButtons('order',[6000,8000,9000,10000]))}${numberField('courtesy','Вежливость аккаунта',state.values.courtesy,0,12000,100,statusBadge(state.values.courtesy,'courtesy'),quickButtons('courtesy',[5000,6000,8000,10000]))}</div>`}
 else if(s==='coaching'){$('#formArea').innerHTML=`<div class="form-grid">${numberField('mmr','MMR клиента',state.values.mmr,0,12000,100,'0–5629: 330 ₽ · 5630–6999: 500 ₽ · 7000+: 700 ₽',quickButtons('mmr',[3000,5000,7000,8000]))}${numberField('hours','Количество часов',state.values.hours,0.5,100,0.5,'Шаг 0,5 часа',quickButtons('hours',[1,2,4,8]))}</div>`}
 else{$('#formArea').innerHTML=`<div class="form-grid"><div class="field full"><label for="tier">Тир боевого кубка</label><select id="tier">${[3,4,5,6,7,8].map(t=>`<option value="${t}">${t} тир — ${money({3:200,4:250,5:300,6:400,7:500,8:1000}[t])}</option>`).join('')}</select><small>Услуга с передачей аккаунта</small></div></div>`;$('#tier').value=state.values.tier}
 bindFields();updateMetrics();calculate();refreshOptionEligibility();}
function bindFields(){document.querySelectorAll('#formArea input,#formArea select').forEach(el=>{el.addEventListener('input',onInput);el.addEventListener('change',onInput);el.addEventListener('blur',()=>commitField(el));});document.querySelectorAll('.number-step').forEach(btn=>btn.addEventListener('click',()=>{const input=$(`#${btn.dataset.for}`);if(!input)return;const min=Number(input.dataset.min)||0,max=Number(input.dataset.max)||9500,step=Number(input.dataset.step)||1,next=Math.min(max,Math.max(min,parseFieldValue(input.value)+Number(btn.dataset.step)));input.value=String(Number(next.toFixed(2))).replace('.',',');onInput({target:input});input.focus();}));document.querySelectorAll('.quick-preset').forEach(btn=>btn.addEventListener('click',()=>{const input=$(`#${btn.dataset.for}`);if(!input)return;input.value=String(btn.dataset.value).replace('.',',');onInput({target:input});input.focus();}));}
function commitField(el){if(!el||!el.dataset.step)return;const min=Number(el.dataset.min)||0,max=Number(el.dataset.max)||9500;const n=Math.min(max,Math.max(min,parseFieldValue(el.value)));el.value=String(n).replace('.',',');state.values[el.id]=n;calculate();}
function onInput(e){const el=e.target;if(el.dataset.addon){state.addons[el.dataset.addon]=el.checked;el.setAttribute('aria-checked',String(el.checked));}else if(el.id in state.values){const cleaned=String(el.value).replace(/[^0-9.,]/g,'').replace(/(,.*),/g,'$1');if(el.value!==cleaned)el.value=cleaned;state.values[el.id]=parseFieldValue(el.value);if(el.dataset.min)state.values[el.id]=Math.max(Number(el.dataset.min),state.values[el.id]);if(el.dataset.max)state.values[el.id]=Math.min(Number(el.dataset.max),state.values[el.id]);}refreshOptionEligibility();calculate();}
function refreshOptionEligibility(){const mmr=state.service==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr;document.querySelectorAll('[data-addon]').forEach(input=>{const def=addonDefs(state.service).find(x=>x[0]===input.dataset.addon);if(!def)return;const eligible=def[3](mmr);input.disabled=!eligible;if(!eligible){input.checked=false;state.addons[input.dataset.addon]=false;}const card=input.closest('.option');card?.classList.toggle('disabled-option',!eligible);input.setAttribute('aria-checked',String(input.checked));});}
function updateMetrics(){if(state.service==='solo'){const add=Math.abs(Number(state.values.target)-Number(state.values.current));$('#metricMmr').textContent=`+${fmt(add)} MMR`;$('#metricBands').textContent=String(bandCount(Number(state.values.current),Number(state.values.target),SOLO_RATES));}}
function coachingRate(m){return m>=7000?700:m>=5630?500:330}function battleRate(t){return({3:200,4:250,5:300,6:400,7:500,8:1000})[t]||0}
function addonRows(mmr,service,base){return D2Pricing.addonBreakdown(mmr,state.addons,service,state.values.order,state.values.courtesy).map(x=>({...x,amount:base*x.percent}));}
function calculate(){const s=state.service;let total=0,base=0,pct=0,route='',rows=[];
 if(s==='solo'){const a=clamp(state.values.current,0,9500),b=clamp(state.values.target,0,9500);base=progressive(a,b,SOLO_RATES);pct=D2Pricing.addonPercent(Math.max(a,b),state.addons,'standard',state.values.order,state.values.courtesy);route=`${fmt(a)} → ${fmt(b)} MMR`;rows=[['Базовая стоимость',money(base)],['MMR к бусту',`+${fmt(Math.abs(b-a))}`]]}
 else if(s==='party'||s==='calibration'){const m=clamp(state.values.mmr,0,9500),wins=clamp(state.values.wins,1,1000),rate=rateFor(m,SERVICES[s].rates);base=rate*wins;pct=D2Pricing.addonPercent(m,state.addons,s,state.values.order,state.values.courtesy);route=`${fmt(m)} MMR · ${fmt(wins)} побед`;rows=[['Ставка',`${money(rate)} / вин`],['Победы',fmt(wins)]]}
 else if(s==='coaching'){const m=clamp(state.values.mmr,0,12000),h=Math.max(.5,Number(state.values.hours)||.5),rate=coachingRate(m);base=rate*h;route=`${fmt(m)} MMR · ${h.toLocaleString('ru-RU')} ч`;total=base;rows=[['Ставка',`${money(rate)} / час`],['Часы',h.toLocaleString('ru-RU')]]}
 else{const tier=Number(state.values.tier)||3;base=battleRate(tier);route=`${tier} тир · передача аккаунта`;total=base;rows=[['Тир',`${tier} тир`],['Формат','С передачей']];}
 if(s==='solo'||s==='party'||s==='calibration'){const addons=addonRows(s==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr,s,base);total=base*(1+pct);if(addons.length)rows.push(...addons.map(x=>[`<span class="breakdown-addon">${x.label}</span>`, `+${Math.round(x.percent*100)}% · ${money(x.amount)}`]));rows.push(['<strong>Доплаты</strong>',pct?`+${Math.round(pct*100)}%`:'Нет']);rows.push(['<strong>Итого доплат</strong>',money(base*pct)]);}
 const priceChip=s==='solo'?`${money(rateFor(Math.max(state.values.current,state.values.target),SOLO_RATES))} / 100 MMR`:s==='coaching'?`${money(coachingRate(state.values.mmr))} / час`:s==='battlecup'?`${money(base)} / заказ`:`${money(rateFor(state.values.mmr,SERVICES[s].rates))} / вин`;
 $('#chipPrice').textContent=priceChip;$('#routeLine').textContent=route;$('#totalPrice').textContent=money(total);$('#resultNote').textContent='Цена обновляется автоматически';$('#summary').innerHTML=rows.map(r=>`<div class="summary-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('');
 refreshStatuses(); updateTable(); saveState();
}
function refreshStatuses(){document.querySelectorAll('.status-badge').forEach(el=>{const id=el.closest('.field')?.querySelector('input')?.id;if(!id)return;const v=state.values[id];el.outerHTML=id==='order'?statusBadge(v,'order'):statusBadge(v,'courtesy');});}
function updateTable(){const s=state.service;$('#tableTitle').textContent=s==='solo'?'Тарифы ММР буста':`Прайс — ${SERVICES[s].title}`;const head=$('#priceTableHead'),body=$('#priceTableBody');if(['solo','party','calibration'].includes(s)){const rates=SERVICES[s].rates;head.innerHTML='<th>Диапазон MMR</th><th>Ставка</th>';body.innerHTML=rates.map(([a,b,r])=>`<tr><td>${fmt(a)}–${fmt(b)}</td><td>${money(r)} / ${s==='solo'?'100 MMR':'вин'}</td></tr>`).join('');$('#tableHint').textContent=s==='solo'?'₽ / 100 MMR':'₽ / вин';return}if(s==='coaching'){head.innerHTML='<th>MMR</th><th>Ставка</th>';body.innerHTML='<tr><td>0–5629</td><td>330 ₽ / час</td></tr><tr><td>5630–6999</td><td>500 ₽ / час</td></tr><tr><td>7000+</td><td>700 ₽ / час</td></tr>';$('#tableHint').textContent='₽ / час';return}head.innerHTML='<th>Тир</th><th>Цена</th><th>Формат</th>';body.innerHTML=[[3,200],[4,250],[5,300],[6,400],[7,500],[8,1000]].map(x=>`<tr><td>${x[0]} тир</td><td>${money(x[1])}</td><td>С передачей</td></tr>`).join('');$('#tableHint').textContent='₽ / заказ';}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.values){Object.assign(state.values,saved.values);state.service=SERVICES[saved.service]?saved.service:'solo';state.addons={doubles:!!saved.addons?.doubles,core:!!saved.addons?.core,smurfpool:!!saved.addons?.smurfpool};}}catch{}}
function saveHistory(){const item={service:SERVICES[state.service].title,route:$('#routeLine').textContent,total:$('#totalPrice').textContent,at:new Date().toLocaleString('ru-RU')};try{const list=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');localStorage.setItem(HISTORY_KEY,JSON.stringify([item,...list].slice(0,6)));renderHistory();}catch{}}
function renderHistory(){const box=$('#historyList');if(!box)return;try{const list=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');box.innerHTML=list.length?list.map(x=>`<button class="history-item" type="button"><span><strong>${x.service}</strong><small>${x.route} · ${x.at}</small></span><b>${x.total}</b></button>`).join(''):'<div class="empty-history">История пока пуста</div>';}catch{box.textContent='История пока недоступна'}}
function buildOrderText(){const addons=D2Pricing.addonBreakdown(state.service==='solo'?Math.max(state.values.current,state.values.target):state.values.mmr,state.addons,state.service,state.values.order,state.values.courtesy);const lines=[`🔥 DOTA BOOST — ЗАКАЗ`,`Услуга: ${SERVICES[state.service].title}`,`Параметры: ${$('#routeLine').textContent}`];if(state.service==='solo'||state.service==='party'||state.service==='calibration'){lines.push(`Порядность: ${fmt(state.values.order)}`,`Вежливость: ${fmt(state.values.courtesy)}`);}if(addons.length)lines.push(`Доплаты: ${addons.map(a=>`${a.label} +${Math.round(a.percent*100)}%`).join(', ')}`);lines.push(`💰 Итого: ${$('#totalPrice').textContent}`);return lines.join('\n')}
function orderTelegram(){saveHistory();const text=encodeURIComponent(buildOrderText());window.open(`https://t.me/share/url?url=${encodeURIComponent(location.href)}&text=${text}`,'_blank','noopener');}
async function copyCalc(){try{await navigator.clipboard.writeText(buildOrderText());$('#copyStatus').textContent='Расчёт скопирован';setTimeout(()=>$('#copyStatus').textContent='',1800)}catch{$('#copyStatus').textContent='Не удалось скопировать'}}
function switchService(s){state.service=s;document.querySelectorAll('.service-tab').forEach(b=>b.classList.toggle('active',b.dataset.service===s));renderFields();window.scrollTo({top:document.querySelector('.service-nav').offsetTop-12,behavior:'smooth'});}
function reset(){state.service='solo';state.values={...DEFAULT};state.addons={};renderFields();}
loadState();
document.querySelectorAll('.service-tab').forEach(b=>b.addEventListener('click',()=>switchService(b.dataset.service)));$('#resetBtn').addEventListener('click',reset);$('#copyBtn').addEventListener('click',copyCalc);$('#orderBtn').addEventListener('click',orderTelegram);$('#saveCalcBtn')?.addEventListener('click',saveHistory);renderFields();renderHistory();
